name: Build, Test, and Deploy

on: 
  [push, workflow_dispatch]

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
        # Checkout the code
        - name: Check Out Code
          uses: actions/checkout@v4

        - name: list files
          run: ls -la

        - name: View requirements.txt file
          run: cat requirements.txt

        - name: View Config file
          run: cat config.py

        - name: Login to docker hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_TOKEN }}

        - name: Build Docker Image
          uses: docker/build-push-action@v2
          with:
            context: .
            file: Dockerfile
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/user-service:dev
            push: true

