name: Testing Build, and Deploy

on: 
  push:
    branches:
      - testing
  workflow_dispatch:

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
        # Checkout the code
        - name: Check Out Code
          uses: actions/checkout@v4

        - name: Login to docker hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_TOKEN }}

        - name: Build Docker Image
          uses: docker/build-push-action@v2
          with:
            context: .
            file: Dockerfile
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/user-service:test
            push: true

        # - name: Deploy to Development
        #   run: |
        #     echo "Deploying to Development"
        #     kubectl apply -f development/dev-user-service.yaml
        #     kubectl rollout restart deployment/dev-user-service


